# Generated by Django 5.0.6 on 2024-06-06 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.BigIntegerField(default=0000000000),
            preserve_default=False,
        ),
    ]
