# Generated by Django 5.0.6 on 2024-06-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_users_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="users",
            name="last_logged_in",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
