# Generated by Django 5.0.6 on 2024-06-05 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.TextField(max_length=20)),
                ("last_name", models.TextField(max_length=20)),
                ("email", models.EmailField(max_length=60)),
                ("password", models.TextField(max_length=300)),
            ],
        ),
    ]
