# Generated by Django 5.0.6 on 2024-06-05 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todos",
            name="created_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
